FROM rust:1 as build-env

WORKDIR /app

COPY backend/ /app

RUN cargo build --release


FROM gcr.io/distroless/cc-debian12:nonroot

USER nonroot

COPY --chown=nonroot:nonroot --from=build-env /app/target/release/zoo_backend  /home/nonroot/

CMD ["/home/nonroot/zoo_backend"]