[package]
name = "server"
version = "0.1.0"
edition = "2021"

[dependencies]
handler = { path = "../handler" }
context = { path = "../context" }
async-graphql = { workspace = true }
async-graphql-axum = { workspace = true }
axum = { workspace = true }
tokio = { workspace = true }
