//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.15

pub use super::channel::Entity as Channel;
pub use super::channel_user::Entity as ChannelUser;
pub use super::message::Entity as Message;
pub use super::role::Entity as Role;
pub use super::user::Entity as User;
pub use super::user_role::Entity as UserRole;
