name: CI

on:
  push:
    paths:
      - "./**"
  workflow_dispatch:


jobs:
  setup:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./backend
    steps:
      - name: Setup Rust
        uses: dtolnay/rust-toolchain@stable
        
      - name: Checkout
        uses: actions/checkout@v4

      - name: Restore Cache
        uses: Swatinem/rust-cache@v2
        with:
          workspaces: backend

  build:
    steps:
      - name: Build project
        run: |
          cargo build

  lint:
    steps:
      - name: lint check
        run: |
          cargo clippy

      - name: format check
        run: |
          cargo fmt --check

  test:
    steps:
      - name: test
        run: |
          cargo test

